FROM rust:alpine as build

ARG STACKS_NODE_VERSION="No Version Info"
ARG GIT_BRANCH='No Branch Info'
ARG GIT_COMMIT='No Commit Info'

WORKDIR /work

RUN apk add --no-cache musl-dev git

RUN mkdir /out

RUN git clone https://github.com/Trust-Machines/stacks-blockchain.git

WORKDIR /work/stacks-blockchain

RUN git checkout next-master-merge

RUN cd testnet/stacks-node && cargo build --features monitoring_prom,slog_json --release

RUN cp target/release/stacks-node /out

FROM alpine

COPY --from=build /out/ /bin/

CMD ["stacks-node", "mainnet"]
