sbtc_contract = "ST2JHG361ZXG51QTKY2NQCVBPPRRE2KZB1HR05NNC.sbtc-alpha"
stacks_private_key="d655b2523bcd65e34889725c73064feb17ceb796831c0e111ba1a552b0f31b3901"
stacks_node_rpc_url = "http://localhost:20443"
bitcoin_node_rpc_url = "http://devnet:devnet@localhost:18443"
frost_dkg_round_id = 0
transaction_fee = 2000
http_relay_url = "http://localhost:9776"
frost_state_file = "frost.state.bin"
network_private_key = "9aSCCR6eirt1NAHwJtSz4HMwBHTyMo62SyPMvVDt5DQn"
network = "testnet"
